# legal_terms.py
legal_terms = {
    "tort": "A tort is a wrongful act leading to legal liability. Examples include negligence, battery, and defamation.",
    "plaintiff": "A plaintiff is the person who brings a case against another in a court of law.",
    "civil law": "Civil law deals with disputes between individuals or organizations, typically involving compensation or legal remedies.",
    "criminal law": "Criminal law involves the state prosecuting someone for violating a law, leading to penalties like fines or imprisonment.",
    "defamation": "Defamation refers to false statements that harm someone's reputation, either through slander (spoken) or libel (written).",
    "contract": "A contract is a legally binding agreement between two or more parties, which can be enforced in court.",
    "negligence": "Negligence refers to the failure to take reasonable care, resulting in harm to another person or their property.",
    "statute": "A statute is a written law passed by a legislative body.",
    "litigation": "Litigation is the process of taking legal action or resolving disputes through the courts.",
    "jurisdiction": "Jurisdiction refers to the authority of a court to hear and decide a case.",
    "appeal": "An appeal is a request to a higher court to review the decision of a lower court.",
    "arbitration": "Arbitration is a method of resolving disputes outside the court system, where an arbitrator makes a binding decision.",
    "mediation": "Mediation is a form of alternative dispute resolution where a neutral third party helps the parties reach a voluntary settlement.",
    "subpoena": "A subpoena is a legal order requiring a person to appear in court or produce documents.",
    "testimony": "Testimony is a formal statement made by a witness under oath during legal proceedings.",
    "bail": "Bail is the temporary release of an accused person pending trial, often with a monetary guarantee.",
    "warrant": "A warrant is an official document authorizing law enforcement to perform a search, seizure, or arrest.",
    "indictment": "An indictment is a formal charge or accusation of a serious crime.",
    "liability": "Liability refers to the legal responsibility for one's actions, especially in cases of negligence or tort.",
    "guilty": "Guilty refers to the legal state of being responsible for committing a crime.",
    "innocent": "Innocent refers to the legal state of not being guilty of a crime.",
    "damages": "Damages refer to the monetary compensation awarded to a party for loss or injury caused by another's wrongful act.",
    "defense": "A defense is an argument or set of arguments presented in court to show that the defendant is not guilty or liable.",
    "prosecution": "The prosecution is the legal party responsible for presenting the case against the defendant in criminal proceedings.",
    "verdict": "A verdict is the decision reached by a jury or judge at the conclusion of a trial.",
    "remedy": "A remedy is a legal solution or compensation awarded to a party in a dispute, often in the form of damages or an injunction.",
    "injunction": "An injunction is a court order requiring a party to do or refrain from doing a specific action.",
    "mistrial": "A mistrial is a trial that is invalid due to an error, such as a hung jury or misconduct.",
    "probation": "Probation is a sentence that allows the offender to serve their time in the community under supervision, instead of in jail.",
    "felony": "A felony is a serious crime, typically punishable by more than one year in prison.",
    "misdemeanor": "A misdemeanor is a less serious crime, typically punishable by less than one year in prison or a fine.",
    "felon": "A felon is a person who has been convicted of a felony.",
    "probable cause": "Probable cause is the legal standard required to make an arrest or conduct a search.",
    "due process": "Due process refers to the legal requirement that the state must respect all legal rights owed to a person.",
    "habeas corpus": "Habeas corpus is a legal principle requiring a person under arrest to be brought before a court to determine if their detention is lawful.",
    "trespass": "Trespass is the unlawful entry onto someone else's land or property without permission.",
    "contempt of court": "Contempt of court refers to behavior that disrespects or disobeys the authority, justice, and dignity of the court.",
    "witness": "A witness is a person who provides evidence or testimony in a case.",
    "contractual obligation": "A contractual obligation refers to a duty or requirement imposed by the terms of a contract.",
    "due diligence": "Due diligence is the process of thoroughly investigating or performing necessary actions before making decisions, particularly in business transactions.",
    "evidence": "Evidence refers to information presented in court to prove or disprove facts in a case.",
    "rights": "Rights are legal, social, or ethical principles of freedom or entitlement.",
    "tortfeasor": "A tortfeasor is an individual or entity responsible for committing a tort.",
    "settlement": "A settlement is an agreement reached between parties in a legal dispute, often outside of court.",
    "testator": "A testator is a person who creates a will.",
    "will": "A will is a legal document that specifies how a person's assets should be distributed after their death.",
    "trust": "A trust is a fiduciary relationship in which one party holds assets for the benefit of another.",
    "bankruptcy": "Bankruptcy is a legal process that allows individuals or businesses to discharge or reorganize their debts.",
    "insolvency": "Insolvency refers to the inability of an individual or business to pay their debts.",
    "patent": "A patent is a form of intellectual property that grants exclusive rights to an invention or process.",
    "trademark": "A trademark is a symbol, word, or other identifier used to distinguish goods or services from others in the market.",
    "copyright": "Copyright is a form of protection granted to the creators of original works, such as books, music, and artwork.",
    "immigration law": "Immigration law governs the rules and policies regarding the entry and stay of people in a country.",
    "family law": "Family law governs legal issues related to family matters, such as divorce, child custody, and adoption.",
    "employment law": "Employment law regulates the relationship between employers and employees, including wages, working conditions, and discrimination.",
    "intellectual property": "Intellectual property refers to creations of the mind, such as inventions, designs, and artistic works, protected by law.",
    "international law": "International law governs the legal relations between sovereign states and other entities in the global community.",
}
